### ISSUE TITLE
Test run shows "N/A" instead of "FF" browser icon and version

### ISSUE THREAD

**Issue by okamara** [zebrunner/javascript-agent-cypress#1]
**Precondition:**
Run test run with Firefox browser

**Steps:**
1. Sign in to tenant with this Test run e.g. https://qps.zebrunner.com/projects/CYP/test-runs
2.  Verify that browser looks correctly in Test Run grid
**Actual result:** Browser is "N/A"
<img width="1227" alt="Снимок экрана 2021-08-10 в 17 34 18" src="https://user-images.githubusercontent.com/32964663/128886439-96703451-f5c0-4bfb-913d-94bda4e36504.png">

**Expected:** Browser is "firefox" icon and version

**Comment by SergeiZagriychuk** [comment]
not reproducing for me locally. please attach console logs of your run so I could investigate

**Comment by ilsenko** [comment]
[firefox : no icon and screenshot.txt](https://github.com/zebrunner/javascript-agent-cypress/files/6966681/firefox.no.icon.and.screenshot.txt)

**Comment by ilsenko** [comment]
firefox icon  appears occasionally with headed and headless run methods
<img width="1347" alt="Screenshot 2021-08-12 at 16 37 52" src="https://user-images.githubusercontent.com/88145209/129207196-61f4deb0-6cdb-43ab-b942-6fb087c7caea.png">
