### ISSUE TITLE
Cypress tests appear to be pending forever

### ISSUE THREAD

**Issue by justinanastos** [zebrunner/javascript-agent-cypress#16]
For some reason my tests never appear to complete.

<img width="73" alt="image" src="https://user-images.githubusercontent.com/5224118/168632830-89339449-7119-4dea-b5ae-b6118f48a14d.png">

**Comment by SergeiZagriychuk** [comment]
hello @justinanastos 
please share more details.
what cypress/agent version do you use? is that cloud version of zebrunner, which version?
if possible please catch and attach some logs related to run finishing. agent logging can be enabled as described here:
https://docs.google.com/document/d/1VSHxOhNOuaFN6toGHci4MpsMHHgTVZxmHtOUuvdLA2Y/edit

**Comment by justinanastos** [comment]
Hi @SergeiZagriychuk ! I'm using Cypress version 9.5.2 and the latest agent version 1.0.24. Specifically the call to `getRunSummary()` is failing with a 404 so the code here never runs, causing the tests to never finish:

https://github.com/zebrunner/javascript-agent-cypress/blob/de84a3513964e2ec3fbc0a0e76495ff6d4fb27d3/lib/process-worker.js#L120-L141

**Comment by SergeiZagriychuk** [comment]
ok, thanks for your reply, I'll take a look

**Comment by MitskevichVS** [comment]
@justinanastos, also fixed in ver. 1.0.32
If you are still experiencing this issue after upgrading to 1.0.32, please open a new issue.
