### ISSUE TITLE
Agent is very chatty with the console

### ISSUE THREAD

**Issue by justinanastos** [zebrunner/javascript-agent-cypress#23]
There are a lot of `console.log`s being written while the reporter is running that don't seem to obey `reportingLoggingEnabled : false` (https://zebrunner.com/documentation/reporting/cypress/#logging).

**Comment by asukhodolova** [comment]
Hi @justinanastos,

Thanks for reporting the ticket.
I would recommend to upgrade to the latest version `1.2.0` - it doesn't include so much `console.log` messages that come from the agent.
It worths to mention - `reportingLoggingEnabled : false` option from https://zebrunner.com/documentation/reporting/cypress/#logging - this parameter enables/disables logging to **file**, not to console output. Sorry for confusing.

I'll close the issue. Thanks.
